/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  EventEmitter,
} from '@stencil/core';
import {
  RouteLinkClickEventDetail,
} from './components/interfaces';
import {
  RouterState,
} from './components/router-state';

declare global {

  namespace StencilComponents {
    interface ThRouteLink {
      'url': string;
    }
  }

  interface HTMLThRouteLinkElement extends StencilComponents.ThRouteLink, HTMLStencilElement {}

  var HTMLThRouteLinkElement: {
    prototype: HTMLThRouteLinkElement;
    new (): HTMLThRouteLinkElement;
  };
  interface HTMLElementTagNameMap {
    'th-route-link': HTMLThRouteLinkElement;
  }
  interface ElementTagNameMap {
    'th-route-link': HTMLThRouteLinkElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-route-link': JSXElements.ThRouteLinkAttributes;
    }
  }
  namespace JSXElements {
    export interface ThRouteLinkAttributes extends HTMLAttributes {
      'onRouteLinkClicked'?: (event: CustomEvent<RouteLinkClickEventDetail>) => void;
      'url'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThRoute {
      'component': string;
      'getState': () => RouterState;
      'isMatch': (newUrl: string) => boolean;
      'setState': (state: number) => void;
      'url': string;
    }
  }

  interface HTMLThRouteElement extends StencilComponents.ThRoute, HTMLStencilElement {}

  var HTMLThRouteElement: {
    prototype: HTMLThRouteElement;
    new (): HTMLThRouteElement;
  };
  interface HTMLElementTagNameMap {
    'th-route': HTMLThRouteElement;
  }
  interface ElementTagNameMap {
    'th-route': HTMLThRouteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-route': JSXElements.ThRouteAttributes;
    }
  }
  namespace JSXElements {
    export interface ThRouteAttributes extends HTMLAttributes {
      'component'?: string;
      'url'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThRouterOutlet {
      'transitionView': (enteringTag: string) => Promise<any>;
    }
  }

  interface HTMLThRouterOutletElement extends StencilComponents.ThRouterOutlet, HTMLStencilElement {}

  var HTMLThRouterOutletElement: {
    prototype: HTMLThRouterOutletElement;
    new (): HTMLThRouterOutletElement;
  };
  interface HTMLElementTagNameMap {
    'th-router-outlet': HTMLThRouterOutletElement;
  }
  interface ElementTagNameMap {
    'th-router-outlet': HTMLThRouterOutletElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-router-outlet': JSXElements.ThRouterOutletAttributes;
    }
  }
  namespace JSXElements {
    export interface ThRouterOutletAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThRouter {

    }
  }

  interface HTMLThRouterElement extends StencilComponents.ThRouter, HTMLStencilElement {}

  var HTMLThRouterElement: {
    prototype: HTMLThRouterElement;
    new (): HTMLThRouterElement;
  };
  interface HTMLElementTagNameMap {
    'th-router': HTMLThRouterElement;
  }
  interface ElementTagNameMap {
    'th-router': HTMLThRouterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-router': JSXElements.ThRouterAttributes;
    }
  }
  namespace JSXElements {
    export interface ThRouterAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;